// swift-tools-version:6.2
// Generated by scripts/lib_publish/publish-libraries.py. Do not edit by hand.
import PackageDescription

let package = Package(
    name: "moot-system",
    platforms: [
        .macOS(.v26),
        .iOS(.v26),
    ],
    products: [
        .library(name: "ConvergenceKit", targets: ["ConvergenceKit"]),
        .library(name: "ConvergenceKitNone", targets: ["ConvergenceKitNone"]),
        .library(name: "ConvergenceKitCloudKit", targets: ["ConvergenceKitCloudKit"]),
        .library(name: "ConvergenceKitFederation", targets: ["ConvergenceKitFederation"]),
        .library(name: "PersistenceKit", targets: ["PersistenceKit"]),
        .library(name: "PersistenceKitInMemory", targets: ["PersistenceKitInMemory"]),
        .library(name: "PersistenceKitSQLite", targets: ["PersistenceKitSQLite"]),
        .library(name: "SQLCipher", targets: ["SQLCipher"]),
        .library(name: "PersistenceKitPostgreSQL", targets: ["PersistenceKitPostgreSQL"]),
        .library(name: "PersistenceKitReplication", targets: ["PersistenceKitReplication"]),
        .library(name: "QueueKit", targets: ["QueueKit"]),
        .library(name: "LoopbackHTTP", targets: ["LoopbackHTTP"]),
        .library(name: "ObserverSink", targets: ["ObserverSink"])
    ],
    dependencies: [
        .package(url: "https://github.com/codedaptive/moot-core.git", branch: "main"),
        .package(url: "https://github.com/vapor/postgres-nio.git", from: "1.21.0"),
        .package(url: "https://github.com/apple/swift-crypto.git", from: "4.0.0"),
        .package(url: "https://github.com/apple/swift-nio-ssl.git", from: "2.25.0")
    ],
    targets: [
        .target(
            name: "ConvergenceKit",
            dependencies: [.product(name: "SubstrateTypes", package: "moot-core"), "PersistenceKit"],
            path: "packages/kits/ConvergenceKit/Sources/ConvergenceKit"
        ),
        .target(
            name: "ConvergenceKitNone",
            dependencies: ["ConvergenceKit", .product(name: "SubstrateTypes", package: "moot-core"), "PersistenceKit"],
            path: "packages/kits/ConvergenceKit/Sources/ConvergenceKitNone"
        ),
        .target(
            name: "ConvergenceKitCloudKit",
            dependencies: ["ConvergenceKit", .product(name: "SubstrateTypes", package: "moot-core"), "PersistenceKit"],
            path: "packages/kits/ConvergenceKit/Sources/ConvergenceKitCloudKit"
        ),
        .target(
            name: "ConvergenceKitFederation",
            dependencies: ["ConvergenceKit", .product(name: "SubstrateTypes", package: "moot-core"), "PersistenceKit", .product(name: "Crypto", package: "swift-crypto")],
            path: "packages/kits/ConvergenceKit/Sources/ConvergenceKitFederation"
        ),
        .target(
            name: "ConvergenceKitConformance",
            dependencies: ["ConvergenceKit", .product(name: "SubstrateTypes", package: "moot-core"), "PersistenceKit", "PersistenceKitInMemory"],
            path: "packages/kits/ConvergenceKit/Tests/ConvergenceKitConformance"
        ),
        .testTarget(
            name: "ConvergenceKitTests",
            dependencies: ["ConvergenceKit", .product(name: "SubstrateTypes", package: "moot-core")],
            path: "packages/kits/ConvergenceKit/Tests/ConvergenceKitTests"
        ),
        .testTarget(
            name: "ConvergenceKitNoneTests",
            dependencies: ["ConvergenceKit", "ConvergenceKitNone", "ConvergenceKitConformance", "PersistenceKitInMemory"],
            path: "packages/kits/ConvergenceKit/Tests/ConvergenceKitNoneTests"
        ),
        .testTarget(
            name: "ConvergenceKitCloudKitTests",
            dependencies: ["ConvergenceKit", "ConvergenceKitCloudKit", "ConvergenceKitConformance", "PersistenceKitInMemory"],
            path: "packages/kits/ConvergenceKit/Tests/ConvergenceKitCloudKitTests"
        ),
        .testTarget(
            name: "ConvergenceKitFederationTests",
            dependencies: ["ConvergenceKit", "ConvergenceKitFederation", "ConvergenceKitConformance", "PersistenceKitInMemory"],
            path: "packages/kits/ConvergenceKit/Tests/ConvergenceKitFederationTests"
        ),
        .target(
            name: "PersistenceKit",
            dependencies: [.product(name: "SubstrateTypes", package: "moot-core"), .product(name: "IntellectusLib", package: "moot-core")],
            path: "packages/kits/PersistenceKit/Sources/PersistenceKit"
        ),
        .target(
            name: "PersistenceKitInMemory",
            dependencies: ["PersistenceKit", .product(name: "SubstrateTypes", package: "moot-core")],
            path: "packages/kits/PersistenceKit/Sources/PersistenceKitInMemory"
        ),
        .target(
            name: "SQLCipher",
            path: "packages/kits/PersistenceKit/Sources/SQLCipher",
            exclude: ["LICENSE.md"],
            publicHeadersPath: "include",
            cSettings: [.define("SQLITE_HAS_CODEC"), .define("SQLCIPHER_CRYPTO_CC"), .define("SQLITE_TEMP_STORE=2"), .define("SQLITE_EXTRA_INIT=sqlcipher_extra_init"), .define("SQLITE_EXTRA_SHUTDOWN=sqlcipher_extra_shutdown"), .define("NDEBUG")],
            linkerSettings: [.linkedFramework("Security")]
        ),
        .target(
            name: "PersistenceKitSQLite",
            dependencies: ["PersistenceKit", .product(name: "SubstrateTypes", package: "moot-core"), "SQLCipher"],
            path: "packages/kits/PersistenceKit/Sources/PersistenceKitSQLite"
        ),
        .target(
            name: "PersistenceKitPostgreSQL",
            dependencies: ["PersistenceKit", .product(name: "SubstrateTypes", package: "moot-core"), .product(name: "PostgresNIO", package: "postgres-nio"), .product(name: "NIOSSL", package: "swift-nio-ssl")],
            path: "packages/kits/PersistenceKit/Sources/PersistenceKitPostgreSQL"
        ),
        .target(
            name: "PersistenceKitReplication",
            dependencies: ["PersistenceKit", .product(name: "SubstrateTypes", package: "moot-core")],
            path: "packages/kits/PersistenceKit/Sources/PersistenceKitReplication"
        ),
        .testTarget(
            name: "PersistenceKitTests",
            dependencies: ["PersistenceKit", .product(name: "SubstrateTypes", package: "moot-core")],
            path: "packages/kits/PersistenceKit/Tests/PersistenceKitTests"
        ),
        .target(
            name: "PersistenceKitConformance",
            dependencies: ["PersistenceKit", .product(name: "SubstrateTypes", package: "moot-core")],
            path: "packages/kits/PersistenceKit/Tests/PersistenceKitConformance"
        ),
        .testTarget(
            name: "PersistenceKitConformanceTests",
            dependencies: ["PersistenceKit", "PersistenceKitConformance", .product(name: "SubstrateTypes", package: "moot-core")],
            path: "packages/kits/PersistenceKit/Tests/PersistenceKitConformanceTests"
        ),
        .testTarget(
            name: "PersistenceKitInMemoryTests",
            dependencies: ["PersistenceKit", "PersistenceKitInMemory", "PersistenceKitConformance", .product(name: "SubstrateTypes", package: "moot-core"), .product(name: "IntellectusLib", package: "moot-core")],
            path: "packages/kits/PersistenceKit/Tests/PersistenceKitInMemoryTests"
        ),
        .testTarget(
            name: "PersistenceKitSQLiteTests",
            dependencies: ["PersistenceKit", "PersistenceKitSQLite", "PersistenceKitConformance", .product(name: "SubstrateTypes", package: "moot-core"), "SQLCipher", .product(name: "IntellectusLib", package: "moot-core")],
            path: "packages/kits/PersistenceKit/Tests/PersistenceKitSQLiteTests"
        ),
        .testTarget(
            name: "PersistenceKitPostgreSQLTests",
            dependencies: ["PersistenceKit", "PersistenceKitPostgreSQL", "PersistenceKitConformance", .product(name: "SubstrateTypes", package: "moot-core")],
            path: "packages/kits/PersistenceKit/Tests/PersistenceKitPostgreSQLTests"
        ),
        .testTarget(
            name: "PersistenceKitReplicationTests",
            dependencies: ["PersistenceKit", "PersistenceKitReplication", "PersistenceKitInMemory", "PersistenceKitSQLite", .product(name: "SubstrateTypes", package: "moot-core"), "SQLCipher"],
            path: "packages/kits/PersistenceKit/Tests/PersistenceKitReplicationTests"
        ),
        .target(
            name: "QueueKit",
            dependencies: [.product(name: "SubstrateTypes", package: "moot-core"), "PersistenceKit", .product(name: "IntellectusLib", package: "moot-core")],
            path: "packages/kits/QueueKit/Sources/QueueKit"
        ),
        .testTarget(
            name: "QueueKitTests",
            dependencies: ["QueueKit", .product(name: "SubstrateTypes", package: "moot-core"), "PersistenceKit", "PersistenceKitInMemory"],
            path: "packages/kits/QueueKit/Tests/QueueKitTests",
            resources: [.copy("Fixtures")]
        ),
        .target(
            name: "LoopbackHTTP",
            path: "packages/libs/LoopbackHTTP/Sources/LoopbackHTTP"
        ),
        .testTarget(
            name: "LoopbackHTTPTests",
            dependencies: ["LoopbackHTTP"],
            path: "packages/libs/LoopbackHTTP/Tests/LoopbackHTTPTests"
        ),
        .target(
            name: "ObserverSink",
            dependencies: [.product(name: "IntellectusLib", package: "moot-core"), "PersistenceKit", "PersistenceKitSQLite"],
            path: "packages/libs/ObserverSink/Sources/ObserverSink"
        ),
        .testTarget(
            name: "ObserverSinkTests",
            dependencies: ["ObserverSink", .product(name: "IntellectusLib", package: "moot-core"), "PersistenceKit", "PersistenceKitSQLite"],
            path: "packages/libs/ObserverSink/Tests/ObserverSinkTests"
        )
    ]
)
